// SheepCalledShip Hunter: full autonomous QA operator.
// Claude calls these functions via MCP tools to run the KAIROS-style loop:
// init -> for each cycle: record findings -> record fixes -> commit -> narrate -> next
//
// The hunter does NOT analyze code or apply fixes. Claude does that.
// The hunter tracks state, generates narrative, manages the session lifecycle.

import * as fs from 'fs';
import * as path from 'path';
import type { SheepConfig, SheepStats, CycleResult, BugReport } from './types.js';
import { autoConfig, generateQAPlan, identifyHighRiskAreas } from './auto-config.js';
import { createStats, loadStats, loadStatsOrRecover, saveStats, completeSession } from './stats.js';
import { generateDeezeebalzRoast, generateMarthaMessage, generateSheepMonologue } from './personas.js';
import { initStory, appendCycle, appendSummary } from './story-writer.js';
import { generateContentPack, formatContentPack } from './content-gen.js';

const SHEEP_DIR = '.sheep';

/**
 * Initializes a Sheep session. Creates .sheep/ with QA plan, stats, story.
 * If a running session exists, resumes from it.
 */
export function initSession(projectRoot: string): {
  config: SheepConfig;
  qaPlan: string;
  stats: SheepStats;
  resumed: boolean;
  preflightUsed: boolean;
  recoveredFromCorruption: boolean;
} {
  // Check for resumable session, gracefully recovering from crash-during-write
  const { stats: existing, corrupted } = loadStatsOrRecover(projectRoot);
  if (existing && existing.status === 'running') {
    const config = autoConfig(projectRoot);
    const qaPlan = generateQAPlan(config);
    return { config, qaPlan, stats: existing, resumed: true, preflightUsed: false, recoveredFromCorruption: false };
  }

  const config = autoConfig(projectRoot);
  const hasPreflightReport = fs.existsSync(path.join(projectRoot, '.preflight', 'report.json'));
  let qaPlan = generateQAPlan(config);
  if (corrupted) {
    qaPlan = `> NOTE: Previous session state corrupted, starting fresh. Old stats saved as stats.json.corrupted.\n\n${qaPlan}`;
  }
  const projectName = path.basename(projectRoot);

  const sheepDir = path.join(projectRoot, SHEEP_DIR);
  if (!fs.existsSync(sheepDir)) fs.mkdirSync(sheepDir, { recursive: true });
  fs.writeFileSync(path.join(sheepDir, 'QA_PLAN.md'), qaPlan, 'utf-8');

  const stats = createStats(projectName);
  saveStats(projectRoot, stats);
  initStory(projectRoot, projectName);

  // Create empty human-review.md
  fs.writeFileSync(
    path.join(sheepDir, 'human-review.md'),
    '# Items for Human Review\nGenerated by SheepCalledShip\n\n',
    'utf-8',
  );

  return { config, qaPlan, stats, resumed: false, preflightUsed: hasPreflightReport, recoveredFromCorruption: corrupted };
}

/**
 * Gets the next area to test based on current cycle count.
 */
export function getNextArea(projectRoot: string): {
  area: string;
  files: string[];
  description: string;
  riskLevel: string;
  cycleNumber: number;
} | null {
  const stats = loadStats(projectRoot);
  if (!stats || stats.status !== 'running') return null;

  const areas = identifyHighRiskAreas(projectRoot);
  const config = autoConfig(projectRoot);

  if (stats.cycleCount >= config.maxCycles) return null;
  if (areas.length === 0) return null;

  const area = areas[stats.cycleCount % areas.length]!;
  return {
    area: area.area,
    files: area.files,
    description: area.description,
    riskLevel: area.riskLevel,
    cycleNumber: stats.cycleCount + 1,
  };
}

/**
 * Records a completed cycle. Called by Claude after analyzing and fixing.
 * Generates persona commentary, writes to stats + story, manages human-review.
 */
export function recordCycleResult(
  projectRoot: string,
  cycle: {
    area: string;
    target: string;
    filesScanned: string[];
    bugsFound: BugReport[];
    bugsFixed: BugReport[];
    bugsLogged: BugReport[];
    buildPassed: boolean;
    testsPassed: boolean;
    testCount: number;
    commitHash: string | null;
  },
): CycleResult {
  const stats = loadStats(projectRoot);
  if (!stats) throw new Error('No active sheep session');

  const cycleNumber = stats.cycleCount + 1;

  // Generate persona commentary
  const firstBug = cycle.bugsFound[0];
  const deezeebalzRoast = firstBug ? generateDeezeebalzRoast(firstBug) : null;
  const marthaMessage = generateMarthaMessage(cycle.area);
  const sheepMonologue = generateSheepMonologue(cycleNumber, cycle.bugsFound.length, cycle.area);

  const result: CycleResult = {
    cycleNumber,
    area: cycle.area,
    target: cycle.target,
    filesScanned: cycle.filesScanned,
    bugsFound: cycle.bugsFound,
    bugsFixed: cycle.bugsFixed,
    bugsLogged: cycle.bugsLogged,
    buildPassed: cycle.buildPassed,
    testsPassed: cycle.testsPassed,
    testCount: cycle.testCount,
    marthaMessage,
    deezeebalzRoast,
    sheepMonologue,
    commitHash: cycle.commitHash,
    timestamp: new Date().toISOString(),
  };

  // Update stats
  stats.cycleCount++;
  stats.bugs.discovered += cycle.bugsFound.length;
  stats.bugs.autoFixed += cycle.bugsFixed.length;
  stats.bugs.logged += cycle.bugsLogged.length;
  stats.files.scanned += cycle.filesScanned.length;
  stats.files.modified += cycle.bugsFixed.length;
  if (cycle.commitHash) stats.commits++;
  stats.tests.after = cycle.testCount;

  // Track areas
  if (!stats.areas.tested.includes(cycle.area)) {
    stats.areas.tested.push(cycle.area);
  }
  if (cycle.bugsFound.length === 0 && !stats.areas.passed.includes(cycle.area)) {
    stats.areas.passed.push(cycle.area);
  } else if (cycle.bugsFound.length > 0 && !stats.areas.failed.includes(cycle.area)) {
    stats.areas.failed.push(cycle.area);
  }

  // Track worst bug
  for (const bug of cycle.bugsFound) {
    if (bug.severity === 'critical' || !stats.worstBug) {
      stats.worstBug = {
        description: bug.description,
        severity: bug.severity,
        file: bug.file,
        howFound: `Cycle ${cycleNumber}, ${cycle.area}`,
      };
    }
  }

  // Track runtime
  const startTime = new Date(stats.sessionStart).getTime();
  stats.totalRuntimeMinutes = Math.round((Date.now() - startTime) / 60000);

  // Store persona content
  if (marthaMessage) stats.marthaMessages.push(marthaMessage);
  if (deezeebalzRoast) stats.deezeebalzRoasts.push(deezeebalzRoast);
  if (sheepMonologue) stats.sheepMonologues.push(sheepMonologue);

  saveStats(projectRoot, stats);
  appendCycle(projectRoot, result);

  // Write logged bugs to human-review
  if (cycle.bugsLogged.length > 0) {
    appendToHumanReview(projectRoot, cycle.bugsLogged);
  }

  return result;
}

/**
 * Completes the session. Generates content pack, writes epilogue.
 */
export function completeHunt(projectRoot: string): {
  stats: SheepStats;
  contentPackPath: string;
} {
  const stats = loadStats(projectRoot);
  if (!stats) throw new Error('No active sheep session');

  completeSession(projectRoot, stats);
  appendSummary(projectRoot, stats);

  const contentPack = generateContentPack(stats);
  const contentPath = path.join(projectRoot, SHEEP_DIR, 'content-pack.md');
  fs.writeFileSync(contentPath, formatContentPack(contentPack), 'utf-8');

  return { stats, contentPackPath: contentPath };
}

/**
 * Generates a session report from current stats.
 */
export function getReport(projectRoot: string): string {
  const stats = loadStats(projectRoot);
  if (!stats) return 'No Sheep session found. Run /linkraft sheep to start.';

  const lines = [
    'SHEEPCALLEDSHIP SESSION REPORT',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    `Project: ${stats.project}`,
    `Status: ${stats.status}`,
    `Runtime: ${stats.totalRuntimeMinutes}m`,
    `Cycles: ${stats.cycleCount}`,
    '',
    `Bugs discovered: ${stats.bugs.discovered}`,
    `Bugs auto-fixed: ${stats.bugs.autoFixed}`,
    `Bugs logged for review: ${stats.bugs.logged}`,
    `Commits: ${stats.commits}`,
    '',
    `Areas tested: ${stats.areas.tested.length} (${stats.areas.tested.join(', ') || 'none yet'})`,
    `Areas clean: ${stats.areas.passed.length}`,
    `Areas with issues: ${stats.areas.failed.length}`,
    '',
    `Files scanned: ${stats.files.scanned}`,
    `Files modified: ${stats.files.modified}`,
    '',
  ];

  if (stats.worstBug) {
    lines.push(`Worst bug: [${stats.worstBug.severity}] ${stats.worstBug.description}`);
    lines.push(`  in ${stats.worstBug.file}`);
    lines.push('');
  }

  if (stats.sheepMonologues.length > 0) {
    lines.push('Latest from the sheep:');
    lines.push(`> ${stats.sheepMonologues[stats.sheepMonologues.length - 1]!}`);
    lines.push('');
  }

  if (stats.marthaMessages.length > 0) {
    lines.push('Latest Martha moment:');
    lines.push(stats.marthaMessages[stats.marthaMessages.length - 1]!);
    lines.push('');
  }

  if (stats.deezeebalzRoasts.length > 0) {
    lines.push('Latest deezeebalz99:');
    lines.push(`> ${stats.deezeebalzRoasts[stats.deezeebalzRoasts.length - 1]!}`);
    lines.push('');
  }

  return lines.join('\n');
}

function appendToHumanReview(projectRoot: string, bugs: BugReport[]): void {
  const filePath = path.join(projectRoot, SHEEP_DIR, 'human-review.md');

  const lines: string[] = [];
  const bySeverity: Record<string, BugReport[]> = {};

  for (const bug of bugs) {
    const sev = bug.severity;
    if (!bySeverity[sev]) bySeverity[sev] = [];
    bySeverity[sev]!.push(bug);
  }

  for (const severity of ['critical', 'high', 'medium', 'low'] as const) {
    const group = bySeverity[severity];
    if (!group || group.length === 0) continue;

    lines.push(`## ${severity.charAt(0).toUpperCase() + severity.slice(1)}`);
    for (const bug of group) {
      lines.push(`- [${bug.id}] ${bug.description}`);
      lines.push(`  File: ${bug.file}${bug.line ? `:${bug.line}` : ''}`);
      if (bug.whyNotFixed) {
        lines.push(`  Why not auto-fixed: ${bug.whyNotFixed}`);
      }
    }
    lines.push('');
  }

  fs.appendFileSync(filePath, lines.join('\n'), 'utf-8');
}
