// Overnight restart loop generator.
//
// When Claude's context window fills, the session dies. Neither dreamroll
// nor sheep can restart themselves from inside — something external has to
// relaunch Claude. This module generates a small shell/PowerShell script
// the user runs in a separate terminal that does exactly that, forever,
// until ctrl+c.
//
// The script is written to the PROJECT ROOT (not .dreamroll/.sheep/) so
// the user sees it immediately and can run it without hunting. The script
// self-locates via $PSScriptRoot or $(dirname $0) so it works no matter
// where the user invokes it from.

import * as fs from 'fs';
import * as path from 'path';

export type OvernightMode = 'dreamroll' | 'sheep';

export interface OvernightScript {
  path: string;
  platform: 'windows' | 'unix';
  content: string;
  /** One-line run command the user copies into a new terminal. */
  runCommand: string;
}

const ALLOWED_TOOLS = "'Bash(*)' 'Read(*)' 'Write(*)' 'Edit(*)' 'Glob(*)' 'Grep(*)'";

function buildWindowsScript(mode: OvernightMode): string {
  return [
    `# ${mode} overnight restart loop`,
    `# Generated by /linkraft ${mode} overnight`,
    '#',
    '# Run this in a separate PowerShell window:',
    `#   powershell -ExecutionPolicy Bypass -File ${mode}-loop.ps1`,
    '#',
    '# The loop relaunches Claude whenever the session ends (context fills,',
    `# error, etc.). ${mode} continues from its state on each restart.`,
    '# Stop with Ctrl+C.',
    '',
    '# Self-locate so claude runs in the project root regardless of cwd',
    'Set-Location -Path $PSScriptRoot',
    '',
    'while ($true) {',
    `  claude -p "/linkraft ${mode}" --allowedTools ${ALLOWED_TOOLS}`,
    '  Start-Sleep -Seconds 10',
    '}',
    '',
  ].join('\n');
}

function buildUnixScript(mode: OvernightMode): string {
  return [
    '#!/usr/bin/env bash',
    `# ${mode} overnight restart loop`,
    `# Generated by /linkraft ${mode} overnight`,
    '#',
    '# Run this in a separate terminal:',
    `#   ./${mode}-loop.sh`,
    '#',
    '# The loop relaunches Claude whenever the session ends (context fills,',
    `# error, etc.). ${mode} continues from its state on each restart.`,
    '# Stop with Ctrl+C.',
    '',
    'set -u',
    '# Self-locate so claude runs in the project root regardless of cwd',
    'cd "$(dirname "${BASH_SOURCE[0]}")"',
    '',
    'while true; do',
    `  claude -p "/linkraft ${mode}" --allowedTools ${ALLOWED_TOOLS}`,
    '  sleep 10',
    'done',
    '',
  ].join('\n');
}

/**
 * Writes the overnight script into the project root. On Unix the script
 * is chmod +x. Returns the full path, content, and the single command the
 * user should run in a new terminal.
 */
export function writeOvernightScript(projectRoot: string, mode: OvernightMode): OvernightScript {
  const isWin = process.platform === 'win32';

  if (isWin) {
    const scriptName = `${mode}-loop.ps1`;
    const scriptPath = path.join(projectRoot, scriptName);
    const content = buildWindowsScript(mode);
    fs.writeFileSync(scriptPath, content, 'utf-8');
    return {
      path: scriptPath,
      platform: 'windows',
      content,
      runCommand: `powershell -ExecutionPolicy Bypass -File "${scriptPath}"`,
    };
  }

  const scriptName = `${mode}-loop.sh`;
  const scriptPath = path.join(projectRoot, scriptName);
  const content = buildUnixScript(mode);
  fs.writeFileSync(scriptPath, content, 'utf-8');
  try {
    fs.chmodSync(scriptPath, 0o755);
  } catch {
    // best effort; on some filesystems chmod is a no-op
  }
  return {
    path: scriptPath,
    platform: 'unix',
    content,
    runCommand: scriptPath,
  };
}

/**
 * Returns the human-readable run instructions for a generated script.
 */
export function overnightInstructions(script: OvernightScript, mode: OvernightMode): string {
  const modeUpper = mode.toUpperCase();

  const lines = [
    `${modeUpper} OVERNIGHT LOOP`,
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    `Script written to: ${script.path}`,
    '',
    'Run this in a NEW terminal window (separate from this Claude session):',
    '',
    `  ${script.runCommand}`,
    '',
    'The loop will keep relaunching Claude every time the context fills.',
    `Each new session reads .${mode}/state.json and continues from where it`,
    'left off. Stop with Ctrl+C.',
    '',
    'Leave your machine plugged in and awake. Turn off display sleep if needed.',
  ];

  return lines.join('\n');
}
