// Overnight restart loop generator.
//
// When Claude's context window fills, the session dies. Sheep can't restart
// itself from inside — something external has to relaunch Claude. This module
// generates a small shell/PowerShell script the user runs in a separate
// terminal that does exactly that, forever, until ctrl+c.
//
// The script is written to the PROJECT ROOT (not .sheep/) so
// the user sees it immediately and can run it without hunting. The script
// self-locates via $PSScriptRoot or $(dirname $0) so it works no matter
// where the user invokes it from.

import * as fs from 'fs';
import * as path from 'path';

export type OvernightMode = 'sheep';

export interface OvernightScript {
  path: string;
  platform: 'windows' | 'unix';
  content: string;
  /** One-line run command the user copies into a new terminal. */
  runCommand: string;
}

const ALLOWED_TOOLS = "'Bash(*)' 'Read(*)' 'Write(*)' 'Edit(*)' 'Glob(*)' 'Grep(*)'";

function buildWindowsScript(mode: OvernightMode): string {
  const title = mode.toUpperCase();
  return [
    `# ${mode} overnight restart loop`,
    `# Generated by /linkraft ${mode} overnight`,
    '#',
    '# Run this in a separate PowerShell window:',
    `#   powershell -ExecutionPolicy Bypass -File ${mode}-loop.ps1`,
    '#',
    '# The loop relaunches Claude whenever the session ends (context fills,',
    `# error, etc.). ${mode} continues from its state on each restart.`,
    '# Stop with Ctrl+C.',
    '',
    '# Self-locate so claude runs in the project root regardless of cwd',
    'Set-Location -Path $PSScriptRoot',
    '',
    '# Startup banner',
    'Write-Host ""',
    `Write-Host "  ${title} OVERNIGHT LOOP" -ForegroundColor Cyan`,
    `Write-Host "  ${'='.repeat(title.length + 15)}" -ForegroundColor DarkCyan`,
    'Write-Host "  Project: $PWD" -ForegroundColor Gray',
    `Write-Host "  Started: $(Get-Date -Format 'yyyy-MM-dd HH:mm')" -ForegroundColor Gray`,
    `Write-Host "  Stop:    Ctrl+C or create .${mode}/STOP file" -ForegroundColor Gray`,
    'Write-Host ""',
    'Write-Host "  Launching first session..." -ForegroundColor Yellow',
    'Write-Host ""',
    '',
    'while ($true) {',
    `  claude -p "/linkraft ${mode}" --allowedTools ${ALLOWED_TOOLS}`,
    '  Write-Host ""',
    `  Write-Host "  [$(Get-Date -Format 'HH:mm')] Session ended. Restarting in 10s..." -ForegroundColor DarkYellow`,
    '  Write-Host ""',
    '  Start-Sleep -Seconds 10',
    '}',
    '',
  ].join('\n');
}

function buildUnixScript(mode: OvernightMode): string {
  const title = mode.toUpperCase();
  // ANSI color codes
  const cyan = '\\033[36m';
  const darkCyan = '\\033[36;2m';
  const gray = '\\033[90m';
  const yellow = '\\033[33m';
  const darkYellow = '\\033[33;2m';
  const reset = '\\033[0m';
  return [
    '#!/usr/bin/env bash',
    `# ${mode} overnight restart loop`,
    `# Generated by /linkraft ${mode} overnight`,
    '#',
    '# Run this in a separate terminal:',
    `#   ./${mode}-loop.sh`,
    '#',
    '# The loop relaunches Claude whenever the session ends (context fills,',
    `# error, etc.). ${mode} continues from its state on each restart.`,
    '# Stop with Ctrl+C.',
    '',
    'set -u',
    '# Self-locate so claude runs in the project root regardless of cwd',
    'cd "$(dirname "${BASH_SOURCE[0]}")"',
    '',
    '# Startup banner',
    'echo ""',
    `echo -e "  ${cyan}${title} OVERNIGHT LOOP${reset}"`,
    `echo -e "  ${darkCyan}${'='.repeat(title.length + 15)}${reset}"`,
    `echo -e "  ${gray}Project: $(pwd)${reset}"`,
    `echo -e "  ${gray}Started: $(date '+%Y-%m-%d %H:%M')${reset}"`,
    `echo -e "  ${gray}Stop:    Ctrl+C or create .${mode}/STOP file${reset}"`,
    'echo ""',
    `echo -e "  ${yellow}Launching first session...${reset}"`,
    'echo ""',
    '',
    'while true; do',
    `  claude -p "/linkraft ${mode}" --allowedTools ${ALLOWED_TOOLS}`,
    '  echo ""',
    `  echo -e "  ${darkYellow}[$(date '+%H:%M')] Session ended. Restarting in 10s...${reset}"`,
    '  echo ""',
    '  sleep 10',
    'done',
    '',
  ].join('\n');
}

/**
 * Writes the overnight script into the project root. On Unix the script
 * is chmod +x. Returns the full path, content, and the single command the
 * user should run in a new terminal.
 */
export function writeOvernightScript(projectRoot: string, mode: OvernightMode): OvernightScript {
  const isWin = process.platform === 'win32';

  if (isWin) {
    const scriptName = `${mode}-loop.ps1`;
    const scriptPath = path.join(projectRoot, scriptName);
    const content = buildWindowsScript(mode);
    fs.writeFileSync(scriptPath, content, 'utf-8');
    return {
      path: scriptPath,
      platform: 'windows',
      content,
      runCommand: `powershell -ExecutionPolicy Bypass -File "${scriptPath}"`,
    };
  }

  const scriptName = `${mode}-loop.sh`;
  const scriptPath = path.join(projectRoot, scriptName);
  const content = buildUnixScript(mode);
  fs.writeFileSync(scriptPath, content, 'utf-8');
  try {
    fs.chmodSync(scriptPath, 0o755);
  } catch {
    // best effort; on some filesystems chmod is a no-op
  }
  return {
    path: scriptPath,
    platform: 'unix',
    content,
    runCommand: scriptPath,
  };
}

/**
 * Returns the human-readable run instructions for a generated script.
 */
export function overnightInstructions(script: OvernightScript, mode: OvernightMode): string {
  const modeUpper = mode.toUpperCase();

  const lines = [
    `${modeUpper} OVERNIGHT LOOP`,
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    `Script written to: ${script.path}`,
    '',
    'Run this in a NEW terminal window (separate from this Claude session):',
    '',
    `  ${script.runCommand}`,
    '',
    'The loop will keep relaunching Claude every time the context fills.',
    `Each new session reads .${mode}/state.json and continues from where it`,
    'left off. Stop with Ctrl+C.',
    '',
    'Leave your machine plugged in and awake. Turn off display sleep if needed.',
  ];

  return lines.join('\n');
}
