// Overnight restart loop generator.
//
// When Claude's context window fills, the session dies. Neither dreamroll
// nor sheep can restart themselves from inside — something external has to
// relaunch Claude. This module generates a small shell/PowerShell script
// the user runs in a separate terminal that does exactly that, forever,
// until ctrl+c.
//
// Both dreamroll and sheep share this. The script is written to the
// mode's state directory (.dreamroll/ or .sheep/) so it sits next to
// state.json and is typically gitignored.

import * as fs from 'fs';
import * as path from 'path';

export type OvernightMode = 'dreamroll' | 'sheep';

export interface OvernightScript {
  path: string;
  platform: 'windows' | 'unix';
  content: string;
}

const ALLOWED_TOOLS = "'Bash(*)' 'Read(*)' 'Write(*)' 'Edit(*)' 'Glob(*)' 'Grep(*)'";

function stateDirFor(mode: OvernightMode): string {
  return mode === 'dreamroll' ? '.dreamroll' : '.sheep';
}

function buildWindowsScript(mode: OvernightMode): string {
  return [
    `# ${mode} overnight restart loop`,
    `# Generated by /linkraft ${mode} overnight`,
    '#',
    '# When Claude Code session ends (context fills or error), this',
    `# relaunches it after 10 seconds. ${mode} continues from its state.json.`,
    '# Stop with Ctrl+C.',
    '',
    'while ($true) {',
    `  claude -p "/linkraft ${mode}" --allowedTools ${ALLOWED_TOOLS}`,
    '  Start-Sleep -Seconds 10',
    '}',
    '',
  ].join('\n');
}

function buildUnixScript(mode: OvernightMode): string {
  return [
    '#!/usr/bin/env bash',
    `# ${mode} overnight restart loop`,
    `# Generated by /linkraft ${mode} overnight`,
    '#',
    '# When Claude Code session ends (context fills or error), this',
    `# relaunches it after 10 seconds. ${mode} continues from its state.json.`,
    '# Stop with Ctrl+C.',
    '',
    'while true; do',
    `  claude -p "/linkraft ${mode}" --allowedTools ${ALLOWED_TOOLS}`,
    '  sleep 10',
    'done',
    '',
  ].join('\n');
}

/**
 * Writes the overnight script for the current OS into the mode's state dir.
 * Makes the Unix version executable. Returns the script path and content.
 */
export function writeOvernightScript(projectRoot: string, mode: OvernightMode): OvernightScript {
  const isWin = process.platform === 'win32';
  const dir = path.join(projectRoot, stateDirFor(mode));
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  if (isWin) {
    const scriptPath = path.join(dir, `${mode}-loop.ps1`);
    const content = buildWindowsScript(mode);
    fs.writeFileSync(scriptPath, content, 'utf-8');
    return { path: scriptPath, platform: 'windows', content };
  }

  const scriptPath = path.join(dir, `${mode}-loop.sh`);
  const content = buildUnixScript(mode);
  fs.writeFileSync(scriptPath, content, 'utf-8');
  try {
    fs.chmodSync(scriptPath, 0o755);
  } catch {
    // best effort; on some filesystems chmod is a no-op
  }
  return { path: scriptPath, platform: 'unix', content };
}

/**
 * Returns the human-readable run instructions for a generated script.
 */
export function overnightInstructions(script: OvernightScript, mode: OvernightMode): string {
  const modeUpper = mode.toUpperCase();
  const dir = path.dirname(script.path);
  const name = path.basename(script.path);

  if (script.platform === 'windows') {
    return [
      `${modeUpper} OVERNIGHT SCRIPT GENERATED`,
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '',
      `Path: ${script.path}`,
      '',
      'To run overnight:',
      '',
      '  1. Open a NEW PowerShell window (separate from this Claude session)',
      `  2. cd "${dir}"`,
      `  3. powershell -ExecutionPolicy Bypass -File ${name}`,
      '',
      'The script relaunches Claude every time the context fills. Each new',
      `session resumes from .${mode}/state.json and continues where it left off.`,
      'Stop with Ctrl+C.',
      '',
      'Leave your laptop plugged in and awake. Disable display sleep if needed.',
    ].join('\n');
  }

  return [
    `${modeUpper} OVERNIGHT SCRIPT GENERATED`,
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    `Path: ${script.path}`,
    '',
    'To run overnight:',
    '',
    '  1. Open a NEW terminal window (separate from this Claude session)',
    `  2. ${script.path}`,
    '',
    'The script relaunches Claude every time the context fills. Each new',
    `session resumes from .${mode}/state.json and continues where it left off.`,
    'Stop with Ctrl+C.',
    '',
    'Leave your laptop plugged in and awake. Disable display sleep if needed.',
  ].join('\n');
}
