import type { ParsedSpec, GeneratorOptions } from '../types.js';

export function generatePluginFiles(
  options: GeneratorOptions,
  spec: ParsedSpec,
  authType: string,
  toolGroups: string[],
): Record<string, string> {
  const files: Record<string, string> = {};
  const name = options.name;
  const desc = options.description ?? spec.description ?? `${spec.title} integration for Claude Code`;

  // package.json
  files['package.json'] = JSON.stringify({
    name: `@linkraft/${name}`,
    version: spec.version,
    description: desc,
    main: 'dist/server.js',
    scripts: {
      build: 'tsc',
      start: 'node dist/server.js',
      typecheck: 'tsc --noEmit',
      test: 'vitest run',
    },
    dependencies: {
      '@linkraft/core': '*',
      '@modelcontextprotocol/sdk': '^1.12.0',
    },
    license: 'MIT',
  }, null, 2) + '\n';

  // tsconfig.json
  files['tsconfig.json'] = JSON.stringify({
    extends: '../../tsconfig.base.json',
    compilerOptions: { outDir: 'dist', rootDir: 'src' },
    include: ['src/**/*.ts'],
    exclude: ['node_modules', 'dist', 'tests'],
  }, null, 2) + '\n';

  // config.example.json
  const configExample: Record<string, unknown> = {
    name,
    version: spec.version,
    auth: { type: authType },
    rateLimits: {
      requestsPerMinute: 60,
      requestsPerDay: 100000,
      retryOnRateLimit: true,
      retryMaxAttempts: 3,
      retryBackoffMs: 1000,
    },
    transport: { type: 'stdio' },
    logging: { level: 'info' },
  };

  if (authType === 'oauth2') {
    (configExample['auth'] as Record<string, unknown>)['clientId'] = 'YOUR_CLIENT_ID';
    (configExample['auth'] as Record<string, unknown>)['clientSecret'] = 'YOUR_CLIENT_SECRET';
  } else {
    const envVar = name.toUpperCase().replace(/-/g, '_');
    (configExample['auth'] as Record<string, unknown>)['apiKey'] = `YOUR_${envVar}_API_KEY`;
  }

  files['config.example.json'] = JSON.stringify(configExample, null, 2) + '\n';

  // .mcp.json
  const envPrefix = name.toUpperCase().replace(/-/g, '_');
  const envVars: Record<string, string> = {};
  if (authType === 'oauth2') {
    envVars[`${envPrefix}_CLIENT_ID`] = '';
    envVars[`${envPrefix}_CLIENT_SECRET`] = '';
  } else {
    envVars[`${envPrefix}_API_KEY`] = '';
  }

  files['.mcp.json'] = JSON.stringify({
    mcpServers: {
      [`linkraft-${name}`]: {
        command: 'node',
        args: ['dist/server.js'],
        env: envVars,
      },
    },
  }, null, 2) + '\n';

  // .claude-plugin/plugin.json
  files['.claude-plugin/plugin.json'] = JSON.stringify({
    name: `linkraft-${name}`,
    version: spec.version,
    description: desc,
    author: 'Generated by Linkraft',
    license: 'MIT',
    skills: [{ name, path: `skills/${name}/SKILL.md` }],
    mcpServers: {
      [`linkraft-${name}`]: {
        command: 'node',
        args: ['dist/server.js'],
      },
    },
  }, null, 2) + '\n';

  // SKILL.md
  files[`skills/${name}/SKILL.md`] = generateSkillMd(name, desc, spec, toolGroups);

  // README.md
  files['README.md'] = generateReadme(name, desc, spec, authType);

  // SETUP.md
  files['SETUP.md'] = generateSetup(name, authType);

  return files;
}

function generateSkillMd(name: string, desc: string, spec: ParsedSpec, toolGroups: string[]): string {
  const lines: string[] = [
    '---',
    `name: ${name}`,
    `description: ${desc}`,
    '---',
    '',
    `# ${toTitleCase(name)} Pack`,
    '',
    desc,
    '',
    '## Available Tools',
    '',
  ];

  for (const group of toolGroups) {
    lines.push(`### ${toTitleCase(group)}`);
    const endpoints = spec.endpoints.filter(e => {
      const tag = e.tags[0] ?? '';
      return tag.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') === group
        || group === 'general';
    });
    for (const ep of endpoints) {
      const toolName = ep.operationId ?? `${ep.method.toLowerCase()}_${ep.path}`;
      const desc = ep.summary ?? ep.description ?? `${ep.method} ${ep.path}`;
      lines.push(`- \`${toolName}\` - ${desc}`);
    }
    lines.push('');
  }

  lines.push(`## Auth`);
  lines.push('');
  lines.push('See SETUP.md for configuration instructions.');
  lines.push('');

  return lines.join('\n');
}

function generateReadme(name: string, desc: string, _spec: ParsedSpec, authType: string): string {
  return `# @linkraft/${name}

${desc}

Generated by [Linkraft](https://github.com/akellaluvlace/Linkraft).

## Quick Start

1. Set up authentication (see [SETUP.md](SETUP.md))
2. Add the MCP server to Claude Code
3. Build: \`npm run build\`

## Auth Type

${authType === 'oauth2' ? 'OAuth 2.0' : authType === 'bearer' ? 'Bearer Token' : 'API Key'}

## Configuration

Copy \`config.example.json\` to \`mcpkit.config.json\` and fill in your credentials.

## License

MIT
`;
}

function generateSetup(name: string, authType: string): string {
  const envPrefix = name.toUpperCase().replace(/-/g, '_');
  const lines: string[] = [
    `# ${toTitleCase(name)} Pack Setup`,
    '',
    '## Prerequisites',
    '',
    '- Node.js >= 18',
    '',
    '## Steps',
    '',
  ];

  if (authType === 'oauth2') {
    lines.push(`1. **Get OAuth credentials** from the API provider`);
    lines.push('');
    lines.push('2. **Set credentials**');
    lines.push('');
    lines.push('   ```bash');
    lines.push(`   export ${envPrefix}_CLIENT_ID="your-client-id"`);
    lines.push(`   export ${envPrefix}_CLIENT_SECRET="your-client-secret"`);
    lines.push('   ```');
  } else {
    lines.push(`1. **Get an API key** from the API provider`);
    lines.push('');
    lines.push('2. **Set the API key**');
    lines.push('');
    lines.push('   ```bash');
    lines.push(`   export ${envPrefix}_API_KEY="your-api-key"`);
    lines.push('   ```');
  }

  lines.push('');
  lines.push('3. **Add to Claude Code**');
  lines.push('');
  lines.push('   Add this to your MCP settings:');
  lines.push('   ```json');
  lines.push('   {');
  lines.push('     "mcpServers": {');
  lines.push(`       "linkraft-${name}": {`);
  lines.push('         "command": "node",');
  lines.push(`         "args": ["path/to/packs/${name}/dist/server.js"]`);
  lines.push('       }');
  lines.push('     }');
  lines.push('   }');
  lines.push('   ```');
  lines.push('');
  lines.push('4. **Build the pack**');
  lines.push('');
  lines.push('   ```bash');
  lines.push(`   cd packs/${name}`);
  lines.push('   npm run build');
  lines.push('   ```');
  lines.push('');

  return lines.join('\n');
}

function toTitleCase(str: string): string {
  return str
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase());
}
